#Todo Dependencias
FROM node:22-alpine AS deps

WORKDIR /usr/src/app

#Habilitar pnpm con core pack
RUN corepack enable

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile


#Todo Builder - Construye la aplicación
FROM node:22-alpine AS build

WORKDIR /usr/src/app

RUN corepack enable

# Copiar de deps, los modulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el codigo fuente de la aplicación
COPY . .

# Run pnpm run test
RUN pnpm run build

RUN pnpm prune --prod


#Todo Crear la imagen final de docker
FROM node:22-alpine AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# Copiar la carpeta de DIST
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD [ "node", "dist/main.js"]
